#include <stdio.h>
#include <stdlib.h>

int main()
{
    int i,j,n;
   /* printf("Hello world!\n");*/
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=15&&j<=20)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=15&&j<=24)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=16&&j<=30)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
            }
            printf("\n");
    }
                for(i=1;i<=1;++i)
               {
        for(j=1;j<=72;++j)
            {
                if(j>=18&&j<=31)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=16&&j<=30)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=2;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=17&&j<=28)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=19&&j<=30)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=19&&j<=26)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=19&&j<=28)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=18&&j<=31)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=16&&j<=31)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=15&&j<=30)||(j>=65&&j<=69))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=13&&j<=30)||(j>=63&&j<=72))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=12&&j<=34)||(j>=62&&j<=71))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
   for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=7&&j<=34)||(j>=58&&j<=69))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=6&&j<=42)||(j>=59&&j<=66))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=7&&j<=67)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=8&&j<=53)||(j>=55&&j<=66))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=9&&j<=52)||(j>=55&&j<=66))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=2&&j<=7)||(j>=9&&j<=51)||(j>=60&&j<=65))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=1&&j<=53)||(j>=60&&j<=64))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=5&&j<=52)||(j>=61&&j<=63))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
   for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=3&&j<=54)||(j>=63&&j<=63))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=5&&j<=10)||(j>=12&&j<=50))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if((j>=6&&j<=10)||(j>=12&&j<=48))
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=13&&j<=47)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=12&&j<=46)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=2;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=13&&j<=42)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=13&&j<=40)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=13&&j<=37)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=14&&j<=37)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
     for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=15&&j<=34)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=16&&j<=31)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=17&&j<=32)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=17&&j<=31)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=18&&j<=31)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=3;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=19&&j<=30)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=21&&j<=28)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=21&&j<=26)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=22&&j<=25)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    for(i=1;i<=1;++i)
    {
        for(j=1;j<=72;++j)
            {
                if(j>=23&&j<=24)
            {
                printf("*");
            }
            else
            {
                printf(" ");
            }
        }
        printf("\n");
    }
    return 0;
}
